return {
    'xiyaowong/nvim-transparent',
    opts = {
        groups = { -- table: default groups
            'Normal',
            'NormalNC',
            'Comment',
            'Constant',
            'Special',
            'Identifier',
            'Statement',
            'PreProc',
            'Type',
            'Underlined',
            'Todo',
            'String',
            'Function',
            'Conditional',
            'Repeat',
            'Operator',
            'Structure',
            'LineNr',
            'NonText',
            'SignColumn',
            'CursorLineNr',
            'EndOfBuffer',
        },
        extra_groups = { -- table/string: additional groups that should be cleared
            -- In particular, when you set it to 'all', that means all available groups

            -- example of akinsho/nvim-bufferline.lua
            'BufferLineTabClose',
            -- 'BufferlineBufferSelected',
            'BufferLineFill',
            'BufferLineBackground',
            'BufferLineSeparator',
            -- 'BufferLineIndicatorSelected',

            -- TODO: needs work, but it is better than default
            'TelescopeBorder',
            'TelescopeMatching',
            'TelescopeMultiIcon',
            -- 'TelescopeMultiSelection',
            'TelescopeNormal',
            'TelescopePreviewBlock',
            'TelescopePreviewBorder',
            'TelescopePreviewCharDev',
            'TelescopePreviewDate',
            'TelescopePreviewDirectory',
            'TelescopePreviewExecute',
            'TelescopePreviewGroup',
            'TelescopePreviewHyphen',
            'TelescopePreviewLine',
            'TelescopePreviewLink',
            'TelescopePreviewMatch',
            'TelescopePreviewMessage',
            'TelescopePreviewMessageFillchar',
            'TelescopePreviewNormal',
            'TelescopePreviewPipe',
            'TelescopePreviewRead',
            'TelescopePreviewSize',
            'TelescopePreviewSocket',
            'TelescopePreviewSticky',
            -- 'TelescopePreviewTitle',
            'TelescopePreviewUser',
            'TelescopePreviewWrite',
            'TelescopePromptBorder',
            'TelescopePromptCounter',
            'TelescopePromptNormal',
            'TelescopePromptPrefix',
            -- 'TelescopePromptTitle',
            -- 'TelescopeResultsBorder',
            -- 'TelescopeResultsClass',
            -- 'TelescopeResultsComment',
            -- 'TelescopeResultsConstant',
            -- 'TelescopeResultsDiffAdd',
            -- 'TelescopeResultsDiffChange',
            -- 'TelescopeResultsDiffDelete',
            -- 'TelescopeResultsDiffUntracked',
            -- 'TelescopeResultsField',
            -- 'TelescopeResultsFunction',
            -- 'TelescopeResultsIdentifier',
            -- 'TelescopeResultsLineNr',
            -- 'TelescopeResultsMethod',
            -- 'TelescopeResultsNormal',
            -- 'TelescopeResultsNumber',
            -- 'TelescopeResultsOperator',
            -- 'TelescopeResultsSpecialComment',
            -- 'TelescopeResultsStruct',
            -- 'TelescopeResultsTitle',
            -- 'TelescopeResultsVariable',
            -- 'TelescopeSelection',
            -- 'TelescopeSelectionCaret',
            -- 'TelescopeTitle',

            -- 'lualine_a_normal',
            -- 'lualine_a_insert',
            'lualine_b_normal',
            'lualine_b_insert',
            'lualine_c_normal',
            'lualine_c_insert',
        },
        exclude_groups = {
            -- 'TelescopeBorder',
        }, -- table: groups you don't want to clear
    },
}
