require('stimpack.boosters.boolean-flipper')
require('stimpack.boosters.line-crusher')
require('stimpack.boosters.save-paragraph')
require('stimpack.boosters.hex-strings')
require('stimpack.boosters.log-timestamp-visualizer')
