-- Based on icons.lua from https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/icons.lua

-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet


Icons = {

    coding = {
        Text = '',
        Method = 'm',
        Function = '',
        Constructor = '',
        Field = '',
        -- variable = "",
        Variable = '',
        Class = '',
        Interface = '',
        Module = '',
        -- module = "",
        Property = '',
        Unit = '',
        Value = '',
        Enum = '',
        -- keyword = "",
        Keyword = '',
        Snippet = '',
        Color = '',
        File = '',
        Reference = '',
        Folder = '',
        Enummember = '',
        Constant = '',
        Struct = '',
        Event = '',
        Operator = '',
        Typeparameter = '',
    },

    type = {
        array = '',
        number = '',
        string = '',
        boolean = '蘒',
        object = '',
    },

    documents = {
        file1 = '',
        file2 = '',
        file3 = '',
        linkedfile = '',
        files = '',
        folder = '',
        write1 = '',
        write2 = '✎',
        opendirectory1 = '',
        opendirectory2 = '',
        opendirectory3 = '',
        flatdirectory = '',
        emptydirectory = '',
        closeddirectory1 = '',
        symlinkdirectory = '',
        cut1 = '',
        cut2 = '✂️',
        cut3 = '✂',
        cut4 = '✄',

    },

    git = {
        git = '',
        unstaged = '✗',
        staged = '✓',
        unmerged = '',
        renamed = '➜',
        untracked = '★',
        deleted = '',
        ignored = '◌',
        add = '',
        mod = '',
        diff = '',
        repo = '',
        octoface = '',
        gutterbar = '▎',
        gutterbar_dashed = '┆',
    },

    ui = {
        arrowclosed1 = '',
        arrowclosed2 = '▸',
        arrowclosed3 = '→',
        arrowclosed4 = '契',
        arrowopen1 = '',
        arrowopen2 = '▾',
        arrowopen3 = '↓',
        rightarrowhollow = '',
        rightarrowfilled = '',
        leftarrowhollow = '',
        leftarrowfilled = '',
        -- arrowopen4 = ,
        lock = '',
        circle = '',
        bigcircle = '',
        bigunfilledcircle = '',
        close = '',
        newfile = '',
        search = '',
        lightbulb = '',
        project = '',
        dashboard = '',
        history = '',
        comment = '',
        bug = '',
        code = '',
        gear = '',
        package = '',
        list = '',
        signin = '',
        signout = '',
        check = '',
        fire = '',
        note = '',
        bookmark = '',
        pencil = '',
        rightarrow = '',
        righthandpoint = ' ',
        -- chevronright = "",
        plus = '➕',
        doublechevron = '»',
        chevronright = '>',
        table = '',
        calendar = '',
        clouddownload = '',
        sign = 'ﲀ',
        stop = '🛑',
        borders = {
            corner = '└',
            edge = '│',
            item = '│',
            bottom = '─',
            none = ' ',
        },
    },

    plugins = {
        telescope = '',
    },

    diagnostics = {
        error1 = '',
        error2 = '❌',
        warning = '',
        information = '',
        question = '',
        hint1 = '',
        hint2 = '💡',
        success = '✔️',
    },

    miscellaneous = {
        fish = '',
        react = ' ',
        brain = ' ',
        robot = 'ﮧ',
        squirrel = '',
        tag = '',
        watch = '',
        smiley = 'ﲃ',
        package = '',
        circuitboard = '',
        tornado = '',
        eye = '👀',
        target = '',
    },

    debugging = {
        bug = '',
    },

    letters = {
        w = '',
    },

    nvim_dev_icon_filetype = function(filetype)
        return (require('nvim-web-devicons').get_icon(nil, filetype)) or '???'
    end,
}
