-- ---@diagnostic disable: redundant-parameter
-- vim.fn.matchadd('Conceal', '[\\ \\]', nil, -1, { conceal = '⬛' })
-- vim.fn.matchadd('Conceal', '[X\\]', nil, -1, { conceal = '✅' })
-- vim.fn.matchadd('Conceal', '[x\\]', nil, -1, { conceal = '✅' })
-- vim.fn.matchadd('Conceal', '[\\.\\]', nil, -1, { conceal = '🐌' })
-- vim.fn.matchadd('Conceal', '[o\\]', nil, -1, { conceal = '🚙' })
-- vim.fn.matchadd('Conceal', '[O\\]', nil, -1, { conceal = '🚁' })
