repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0

  # https://github.com/JohnnyMorganz/StyLua
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      # id: stylua uses cargo to install
      # id: stylua-system checks system path for binary
      # id: stylua-github is a GitHub action
      - id: stylua
