-- Get lists of items
local function GetCompletion(item_name)
    -- for _, v in pairs(vim.fn.getcompletion('', item_name)) do
    --   print(v)
    -- end
    return vim.fn.getcompletion('', item_name)
end

print(GetCompletion('arglist'))
print(GetCompletion('augroup'))
print(GetCompletion('buffer'))
print(GetCompletion('behave'))
print(GetCompletion('cmdline'))
print(GetCompletion('color'))
print(GetCompletion('command'))
print(GetCompletion('compiler'))
print(GetCompletion('cscope'))
print(GetCompletion('diff_buffer'))
print(GetCompletion('dir'))
print(GetCompletion('environment'))
print(GetCompletion('event'))
print(GetCompletion('expression'))
print(GetCompletion('file'))
print(GetCompletion('file_in_path'))
print(GetCompletion('filetype'))
print(GetCompletion('function'))
print(GetCompletion('help'))
print(GetCompletion('highlight'))
print(GetCompletion('history'))
print(GetCompletion('locale'))
print(GetCompletion('mapclear'))
print(GetCompletion('mapping'))
print(GetCompletion('menu'))
print(GetCompletion('messages'))
print(GetCompletion('option'))
print(GetCompletion('packadd'))
print(GetCompletion('shellcmd'))
print(GetCompletion('sign'))
print(GetCompletion('syntax'))
print(GetCompletion('syntime'))
print(GetCompletion('tag'))
print(GetCompletion('tag_listfiles'))
print(GetCompletion('user'))
print(GetCompletion('var'))
